os: linux
dist: xenial
language: python
python: "3.8"
addons:
    apt:
        packages:
            - ffmpeg  # this is required which include libSDL2-2.0.so.0
# command to install dependencies
install:
  - pip install PyPubSub
  - pip install youtube_dl
  - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk2/ubuntu-16.04/wxPython-4.1.0-cp38-cp38-linux_x86_64.whl wxPython
# command to run tests
script:
  - python tests/test_check_bin.py
  - python tests/test_ffprobe.py
  - python launcher

