theme: jekyll-theme-midnight
show_downloads: true
title: Videomass2
description: Videomass2 is a free, open source and cross-platform GUI for FFmpeg
header_pages:
    - about.md
    - features.md
    - screenshot.md
    - getting_started.md
    - donation.md
    - LICENSE
