theme: jekyll-theme-midnight
show_downloads: true
title: Videomass2
description: Videomass2 is a free, open source and cross-platform GUI for FFmpeg
header_pages:
    - about.md
    - features.md
    - screenshot.md
    - LICENSE
    - other_resources.md
    - installation.md
    - execute_sources.md
    - dependencies.md
    - building_package.md
    - videomass_use.md
    - known_problems.md
    - donation.md
