theme: jekyll-theme-midnight
remote_theme: pmarsceill/just-the-docs
show_downloads: true
title: Videomass
description: Videomass is a free, open source and cross-platform GUI for FFmpeg and youtube-dl
header_pages:
    - about.md
    - features.md
    - screenshots.md
    - LICENSE
    - download_installation.md
    - prests_update.md
    - videomass_use.md
    - tips_and_tricks.md
    - known_problems.md
    - donation.md
