theme: jekyll-theme-midnight
show_downloads: true
title: Videomass
description: Videomass is a free, open source and cross-platform GUI for FFmpeg
header_pages:
    - about.md
    - features.md
    - screenshot.md
    - LICENSE
    - download_installation.md
    - videomass_use.md
    - tips_and_tricks.md
    - known_problems.md
    - donation.md
